from enum import StrEnum


class GenerationOrigin(StrEnum):
    GENERIC = "generic"
    QUESTIONNAIRE = "questionnaire"
    ADMIN_SANDBOX = "admin_sandbox"
    ADMIN_ORBIT = "admin_orbit"


QUESTIONNAIRE_PROMPT_PREFIX = "AUROOM_RENDER_SPEC_V1"
INITIAL_CONCEPT_PROMPT_PREFIX = "AUROOM_INITIAL_CONCEPT_V1"
ADMIN_SANDBOX_PROMPT_PREFIX = "AUROOM_ADMIN_SANDBOX_V1\\n"
ADMIN_ORBIT_PROMPT_PREFIX = "AUROOM_ADMIN_ORBIT_V1\\n"

RESERVED_INTERNAL_PROMPT_PREFIXES = (
    QUESTIONNAIRE_PROMPT_PREFIX,
    INITIAL_CONCEPT_PROMPT_PREFIX,
    ADMIN_SANDBOX_PROMPT_PREFIX,
    ADMIN_ORBIT_PROMPT_PREFIX,
)
